// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var h_size, i, imageAdjust, j, linkBtnPositioning, resizeText, shuffleImg, w_size;
    w_size = $(window).width();
    h_size = $(window).height();
    $(window).on('load', function() {
      imageAdjust();
      resizeText();
      return linkBtnPositioning();
    });
    $(window).on('resize', function() {
      w_size = $(window).width();
      h_size = $(window).height();
      imageAdjust();
      resizeText();
      return linkBtnPositioning();
    });
    linkBtnPositioning = function() {
      var btn_height, footer_top;
      footer_top = $('#footer').offset().top;
      btn_height = $('.linkBtnArea .linkBtn').height();
      return $('.linkBtnArea').css('top', footer_top - btn_height);
    };
    imageAdjust = function() {
      if (w_size > 480) {

        /* without mobile */
        $('#mainVisual ul li').find('img').each(function() {
          var $this, dispAsp, h, imgAsp, w;
          $this = $(this);
          w = w_size;
          h = h_size;
          imgAsp = $this.width() / $this.height();
          dispAsp = w / h;
          if (imgAsp > dispAsp) {
            return $this.css({
              "width": 'auto',
              "height": h,
              "margin-top": 0,
              "margin-left": (w - $this.width()) / 2
            });
          } else {
            return $this.css({
              "width": '100%',
              "height": 'auto',
              "top": 'auto',
              "margin-top": (h - $this.height()) / 2,
              "margin-left": 0
            });
          }
        });
      } else {

        /* mobile */
        return $('#mainVisual ul li').not('.lastSlide').find('img').each(function() {
          var $this, _a, _src;
          $this = $(this);
          _a = $this.attr('src').split('/');
          _src = _a[0] + "/" + _a[1] + "/" + _a[2] + "/w640/" + _a[4];
          return $this.attr('src', _src);
        });
      }
    };
    shuffleImg = function(_target_no) {
      var _current, _img, _prefix, _rand, _rand_base, _slide_no, _src;
      _current = $('#mainVisual ul').find('li').eq(_target_no);
      _img = _current.find('img');
      _slide_no = _target_no + 1;
      _prefix = '';
      switch (_slide_no) {
        case 1:
          _rand_base = $('#set_count_01').data('set-count') || 20;
          break;
        case 2:
          _rand_base = $('#set_count_02').data('set-count') || 20;
          break;
        case 3:
          _rand_base = $('#set_count_03').data('set-count') || 20;
          break;
        case 4:
          _rand_base = $('#set_count_04').data('set-count') || 20;
          break;
        case 5:
          _rand_base = $('#set_count_05').data('set-count') || 20;
          break;
        case 6:
          _rand_base = $('#set_count_06').data('set-count') || 20;
          break;
        case 7:
          _rand_base = $('#set_count_07').data('set-count') || 20;
          break;
        case 8:
          _rand_base = $('#set_count_08').data('set-count') || 20;
          break;
        case 9:
          _rand_base = $('#set_count_09').data('set-count') || 20;
          break;
        case 10:
          _rand_base = $('#set_count_10').data('set-count') || 20;
      }
      _rand = parseInt(Math.random() * _rand_base) + 1;
      _rand = ('0' + _rand).slice(-2);
      if ($(window).width() <= 480) {
        _prefix = '/w640';
      }
      _src = './images/slide_' + _slide_no + _prefix + '/image' + _rand + '.jpg';
      _img.attr('src', _src);
    };
    resizeText = function() {
      var _fz;
      if (w_size > 1240) {
        _fz = w_size / 1240 * 100;
        return $('html').css({
          'font-size': _fz + '%'
        });
      } else {
        return $('html').css({
          'font-size': '100%'
        });
      }
    };

    /* init slide */
    for (i = j = 0; j <= 5; i = ++j) {
      shuffleImg(i);
    }
    $('#mainVisual').flexslider({
      controlNav: false,
      directionNav: false,
      animationSpeed: 1000,
      slideshowSpeed: 2500,
      start: function(slider) {
        imageAdjust();
      },
      before: function(slider) {
        var _current_no, _target_no;
        imageAdjust();
        _current_no = slider.currentSlide;
        _target_no = _current_no - 1;
        if (_target_no < 0 || _target_no >= 6) {
          _target_no = slider.count - 1;
        } else {
          shuffleImg(_target_no);
        }
        if (_current_no === 7) {
          return setTimeout(function() {
            return $('#linkBtnArea').fadeIn(800);
          }, 500);
        }
      },
      end: function(slider) {
        slider.pause();
        return setTimeout(function() {
          return slider.play();
        }, 500);/* 元々は13000 */
      }
    });
  });

}).call(this);
