// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var _auto_play_target, _count, _list_w, _loop_w, _showcase_h, _showcase_w, auto_play_flg, auto_play_timer, ie8_flg, loopSliderInit, switchImage, switchSet, ua, ver;
    auto_play_flg = true;
    auto_play_timer = '';
    _showcase_w = 0;
    _showcase_h = 0;
    _count = 0;
    _list_w = 0;
    _loop_w = 0;
    $.fx.interval = 7;
    ua = window.navigator.userAgent.toLowerCase();
    ver = window.navigator.appVersion.toLowerCase();
    ie8_flg = ua.indexOf("msie") !== -1 && ver.indexOf("msie 8.") !== -1;
    $('#menu').find('li a').not('.outerLink').on('mouseenter', function() {
      $(this).closest('li').addClass('hover').append('<div class="bg">');
      return $('.bg').animate({
        'width': '100%',
        'opacity': '1'
      });
    }).on('mouseleave', function() {
      return $(this).closest('li').find('.bg').animate({
        'width': '0%',
        'opacity': '0'
      }, function() {
        return $(this).closest('li').removeClass('hover').end().remove();
      });
    });
    loopSliderInit = function() {
      var _duration, loopsliderPosition;
      _showcase_w = $('#showcase').width();
      _showcase_h = $('#showcase').height();
      _count = $('#showcase').find('li').size();
      _list_w = parseInt(_showcase_w / 5, 10);
      _loop_w = _list_w * _count;
      $('#showcase').find('ul').wrapAll('<div id="showcaseWrapper">').end().find('li').width(_list_w);
      _duration = _count * 4000;
      _duration = _duration / 1000;
      $('#showcaseWrapper').width(_loop_w * 2).height(_showcase_h).css({
        'left': 0
      });
      loopsliderPosition = function() {
        return $('#showcaseWrapper').animate({
          'left': '-' + _loop_w + 'px'
        }, _duration * 1000, 'linear', function() {
          $('#showcaseWrapper').css({
            'left': 0
          });
          return loopsliderPosition();
        });
      };
      setTimeout(function() {
        return loopsliderPosition();
      }, _duration);
      return $('#showcase').find('ul').clone().appendTo('#showcaseWrapper');
    };
    switchImage = function(_src) {
      var _img, _old_img, _old_img_h, _old_img_w;
      _old_img_h = $('#mainVisual').height();
      _old_img_w = $('#mainVisual').width();
      _old_img = $('#mainVisual').addClass('loading').find('img').css({
        'opacity': 0
      });
      _img = new Image();
      _img.src = _src;
      return $(_img).on('load', function() {
        _old_img.remove();
        return $('#mainVisual').removeClass('loading').append($(this));
      });
    };
    switchSet = function(target) {
      var _set_class, _set_code;
      _set_code = target.attr('href').slice('6');
      _set_class = '.set_0' + _set_code;
      $('#menu').find('li').removeClass('current');
      target.closest('li').addClass('current');
      $('.title').find('p').fadeOut().end().find(_set_class).fadeIn();
      return $('#main').find('.view').fadeOut().end().find('#showcase').fadeOut(function() {
        var _first_image_src, _image_src, _list_size, _num, i, j, ref, url_array, url_prefix;
        url_array = location.pathname.split('/');
        url_prefix = '';
        if (url_array[2] === 'archives') {
          url_prefix = '/' + url_array[1] + '/' + url_array[2] + '/' + url_array[3];
        }
        _first_image_src = url_prefix + ("/images/slide_" + _set_code + "/image01.jpg");
        switchImage(_first_image_src);
        switch (_set_code) {
          case '1':
            _list_size = $('#set_count_01').data('set-count') || 30;
            break;
          case '2':
            _list_size = $('#set_count_02').data('set-count') || 30;
            break;
          case '3':
            _list_size = $('#set_count_03').data('set-count') || 30;
            break;
          case '4':
            _list_size = $('#set_count_04').data('set-count') || 30;
            break;
          case '5':
            _list_size = $('#set_count_05').data('set-count') || 30;
            break;
          case '6':
            _list_size = $('#set_count_06').data('set-count') || 30;
        }
        $('#main').find('#showcase').find('ul').remove().end().append('<ul>').find('#showcaseWrapper').remove();
        for (i = j = 1, ref = _list_size; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
          _num = parseInt(i);
          _num = ('0' + _num).slice(-2);
          _image_src = url_prefix + ("/images/slide_" + _set_code + "/w320/image" + _num + ".jpg");
          $('#main').find('#showcase').find('ul').append('<li><a href="#"><img src="' + _image_src + '"></a></li>');
        }
        loopSliderInit();
        return $('#main').find('.view, .title, #showcase').fadeIn();
      });
    };
    $('#menu').find('li a').not('.outerLink').on('click', function(e) {
      e.preventDefault();
      switchSet($(this));
      return auto_play_flg = false;
    });
    _auto_play_target = $('#menu').find('.current').find('a');
    $(window).on('load', function() {
      return switchSet(_auto_play_target);
    });
    auto_play_timer = setInterval(function() {
      var _next;
      if (auto_play_flg === true) {
        _next = $('#menu').find('.current').next('li');
        if (_next.size()) {
          _auto_play_target = $('#menu').find('.current').next('li').find('a');
        } else {
          _auto_play_target = $('#menu').find('li:first-child').find('a');
        }
        return switchSet(_auto_play_target);
      } else {
        return clearInterval(auto_play_timer);
      }
    }, 8000);
    $('#main').on('click', '#showcase a', function(e) {
      var _img_src, _src;
      e.preventDefault();
      _src = $(this).find('img').attr('src').split('/');
      if (_src[5]) {
        _img_src = "/" + _src[1] + "/" + _src[2] + "/" + _src[3] + "/" + _src[4] + "/" + _src[5] + "/" + _src[7];
      } else {
        _img_src = "/" + _src[1] + "/" + _src[2] + "/" + _src[4];
      }
      return switchImage(_img_src);
    });
    $('#navArchives').on('mouseenter', function(e) {
      var $this;
      $this = $(this);
      $this.addClass('is-open');
      return $this.find('.navArchives_title').next('ul').slideDown();
    }).on('mouseleave', function(e) {
      var $this;
      $this = $(this).closest('#navArchives');
      $this.removeClass('is-open');
      return $this.find('.navArchives_title').next('ul').slideUp();
    });
  });


  const mql = window.matchMedia('(max-width: 480px)');

  // MediaQueryListにイベントリスナを登録
  mql.addListener(handleWidthChange);

  // 初期状態の評価のため
  // イベントリスナを一度実行しておく
  handleWidthChange(mql);

  // イベントリスナの定義
  function handleWidthChange(mql) {
    $('.js-clone').remove();
    if (mql.matches) {
      // SP
      $('#main').hide().clone().addClass('js-clone').show().prependTo('body');
      $('#side h1').hide().clone().addClass('js-clone').show().prependTo('body');
    } else {
      // PC
      $('#main').show();
      $('#side h1').show();
    }
  }
}).call(this);
